### PR TITLE
Document the existing matchers that are available

### PR DESCRIPTION
**Pull request by kevinkirkup**
Document the existing set of matchers that are available
based on the current unit tests.

### CODE REVIEW

**Comment by alilosoft** [comment]
Hi, 
This is a nice addition to the doc but It would be nicer if you put the examples in code blocks to be more readable.
```kotlin
expect(actual).toBe(object)
expect(actual).toBeTheSameAs(object)
expect(actual).toNotBeTheSameAs(object)
.....
```

**Comment by kevinkirkup** [comment]
Yeah I can do that.

**Comment by kevinkirkup** [comment]
Updated. Any idea when this could be merged?
If it doesn't get some love soon, I may end up forking it.
I'd rather not though...

**Comment by kevinkirkup** [comment]
Closing due to inactivity.

**Pull request closed without merging**
